[package]
name = "gb_decompiler"
version = "0.1.0"
edition = "2024"

[workspace]
members = [ "codegen" ]

[dependencies]
codegen = { path = "codegen" }

[build-dependencies]
codegen = { path = "codegen" }
