[package]
name = "gb_decompiler"
version = "0.1.0"
edition = "2024"

[dependencies]
codegen = { path = "codegen" }

[build-dependencies]
codegen = { path = "codegen" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
